SystemUI: Introduce user interface for Alert Sliders.
Ported from OxygenOS and reworked for our alert slider
implementation. We target AudioManager instead of Zen,
icons are also the same as aosp and the dialog uses the
material theme as well as support for our themes.

To use, the alert slider config must be enabled. By default,
the dialog shows on the left side. To move it to the right
side, set the location config to 1.

Adapt for A13: SuperDroidBond

In A13, Google has changed the Volume Dialog Crontroller's method of onShowRequested(int) to onShowRequested(int, boolean, int) which causes build errors.

error:
<anonymous com.android.systemui.tristate.TriStateUiControllerImpl$1> is not abstract and does not override abstract method onShowRequested(int,boolean,int) in Callbacks

Solution:
Seach "Move Volume control Binder calls to worker thread" method to get the idea directly.

Change-Id: Ie1954a44cc5242c95a731abd7404379ea638fe70
Signed-off-by: SuperDroidBond <superdroidbond@yahoo.com>
Signed-off-by: Jackeagle <jackeagle102@gmail.com>