Update patch set 4
Patch Set 4:

PS3:
 *** FATAL EXCEPTION IN SYSTEM PROCESS: main
 java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.headset.profile.action.ACTIVE_DEVICE_CHANGED flg=0x5000010 (has extras) } in com.android.server.audio.AudioService$AudioServiceBroadcastReceiver@5059cda
 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
 	at android.os.Handler.handleCallback(Handler.java:883)
 	at android.os.Handler.dispatchMessage(Handler.java:100)
 	at android.os.Looper.loop(Looper.java:214)
 	at com.android.server.SystemServer.run(SystemServer.java:563)
 	at com.android.server.SystemServer.main(SystemServer.java:357)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:893)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
 	at com.android.server.audio.AudioDeviceInventory.startMusicPlayer(AudioDeviceInventory.java:944)
 	at com.android.server.audio.BtHelper.handleBtScoActiveDeviceChange(BtHelper.java:583)
 	at com.android.server.audio.BtHelper.setBtScoActiveDevice(BtHelper.java:605)
 	at com.android.server.audio.BtHelper.receiveBtEvent(BtHelper.java:256)
 	at com.android.server.audio.AudioDeviceBroker.receiveBtEvent(AudioDeviceBroker.java:171)
 	at com.android.server.audio.AudioService$AudioServiceBroadcastReceiver.onReceive(AudioService.java:5832)
 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1550)

Patch-set: 4